spring.application.name=bigtik

spring.datasource.url=jdbc:sqlite:bigtik.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.sql.init.mode=always

spring.messages.basename=messages
spring.messages.encoding=UTF-8

video.upload.path=${user.dir}/uploads/videos
video.max.size=5368709120
images.upload.path=${user.dir}/uploads/images


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB
